import{a as L,i as m,S as b}from"./assets/vendor-09d7c26e.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();async function g(r,t,a=15){const s={http:"https://pixabay.com/api/",key:"43793393-3131be18ae161d81d2e9721c8",options:"image_type=photo&orientation=horizontal&safesearch=true"},e={key:s.key,q:r,per_page:a,page:t,...Object.fromEntries(new URLSearchParams(s.options))},{data:o}=await L.get(s.http,{params:e});if(o.totalHits){const n=Math.ceil(o.totalHits/a);window.totalPages=n}return o.hits}const i={searchForm:document.querySelector(".search-bar-form"),searchInput:document.querySelector("#search-bar"),searchButton:document.querySelector("button"),galleryList:document.querySelector(".gallery-list"),extensionButton:document.querySelector(".extentionButton")};function w(){return new b(".image-card-link",{caption:!0,captionSelector:"img",captionType:"attr",captionsData:"alt",captionDelay:250,captionPosition:"bottom"})}function v(){m.settings({timeout:5e3,titleColor:"#fff",position:"topRight",messageColor:"#fff",icon:"",close:!1})}let f=!1;function d(r="Sorry, there are no images matching your search query. Please try again!"){f||(v(),m.error({message:r,class:"error-notification",timeout:5e3,iconUrl:"/img/octagon.svg",titleColor:"#fff",position:"topRight",backgroundColor:"red",messageColor:"#fff",progressBarColor:"#B51B1B",close:!0}),f=!0)}function p(r){const t=document.querySelector(".gallery-list"),a=r.map(({webformatURL:s,largeImageURL:e,tags:o,likes:n,views:y,comments:B,downloads:x})=>`
    <li class="image-card">
      <a href="${e}" class="image-card-link">
        <img src="${s}" width="360" height="200" class="image-card-thumb" alt="${o}">
        <ul class="image-card-details-list">
          <li class="image-card-details-list-item">
            <p class="image-card-details-title">Likes</p>
            <p class="image-card-details-text">${n}</p>
          </li>
          <li class="image-card-details-list-item">
            <p class="image-card-details-title">Views</p>
            <p class="image-card-details-text">${y}</p>
          </li>
          <li class="image-card-details-list-item">
            <p class="image-card-details-title">Comments</p>
            <p class="image-card-details-text">${B}</p>
          </li>
          <li class="image-card-details-list-item">
            <p class="image-card-details-title">Downloads</p>
            <p class="image-card-details-text">${x}</p>
          </li>
        </ul>
      </a>
    </li>`).join("");t.insertAdjacentHTML("beforeend",a),w().refresh()}function S(){l>=window.totalPages&&(i.extensionButton.style.display="none",m.error({message:"We're sorry, there are no more posts to load",class:"error-notification",timeout:5e3,iconUrl:"/img/octagon.svg",titleColor:"#fff",position:"topRight",backgroundColor:"red",messageColor:"#fff",progressBarColor:"#B51B1B",close:!0}))}function u(r){document.querySelector(".loader").classList.toggle("is-active",r)}let h=15,c="",l=1;function C(){i.galleryList.innerHTML=""}i.searchForm.dataset.listenerAttached||(i.searchForm.dataset.listenerAttached="true",i.searchForm.addEventListener("submit",async r=>{if(r.preventDefault(),C(),c=i.searchInput.value.trim(),l=1,c===""){i.extensionButton.style.display="none",d("Please enter a search term.");return}i.extensionButton.style.display="none",u(!0),setTimeout(async()=>{try{const t=await g(c,l,h);p(t),i.galleryList.childElementCount<=0&&d("No images found."),t.length>0?(i.extensionButton.style.display="block",i.extensionButton.classList.remove("extentionButton"),i.extensionButton.classList.add("div-button")):i.extensionButton.style.display="none"}catch(t){console.error("Error fetching or updating images:",t),d("An error occurred while fetching images.")}finally{u(!1)}},1e3),i.searchInput.value=""}));i.extensionButton.dataset.listenerAttached||(i.extensionButton.dataset.listenerAttached="true",i.extensionButton.addEventListener("click",async r=>{r.preventDefault(),u(!0),l+=1,setTimeout(async()=>{try{const t=await g(c,l,h);p(t),S(),P()}catch(t){console.error("Error fetching or updating images:",t)}finally{u(!1)}},1e3)}));function P(){const t=i.galleryList.getBoundingClientRect().height*2,a=500,s=t/(1e3/a);let e=0;const o=setInterval(()=>{window.scrollBy({top:s,left:0,behavior:"smooth"}),e+=s,e>=t&&clearInterval(o)},a)}
//# sourceMappingURL=commonHelpers.js.map
